// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPwaKi8cDE3VNY9TbkwgsPEARXRBP6o5g',
    appId: '1:184831115274:web:4515860d63b431462adff3',
    messagingSenderId: '184831115274',
    projectId: 'qpay-pos',
    authDomain: 'qpay-pos.firebaseapp.com',
    storageBucket: 'qpay-pos.appspot.com',
    measurementId: 'G-PNCJ7D952Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT5NPy_R3ebTSG5DpWCVRsfkFZSSUk9S4',
    appId: '1:184831115274:android:e487e1a70d3b7ef12adff3',
    messagingSenderId: '184831115274',
    projectId: 'qpay-pos',
    storageBucket: 'qpay-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcg_8GkDvig1fEAW_gT03wgr5dig8dcq4',
    appId: '1:184831115274:ios:70156cfc3d94e5412adff3',
    messagingSenderId: '184831115274',
    projectId: 'qpay-pos',
    storageBucket: 'qpay-pos.appspot.com',
    iosBundleId: 'com.qpay.qpayClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcg_8GkDvig1fEAW_gT03wgr5dig8dcq4',
    appId: '1:184831115274:ios:70156cfc3d94e5412adff3',
    messagingSenderId: '184831115274',
    projectId: 'qpay-pos',
    storageBucket: 'qpay-pos.appspot.com',
    iosBundleId: 'com.qpay.qpayClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPwaKi8cDE3VNY9TbkwgsPEARXRBP6o5g',
    appId: '1:184831115274:web:9abfefedaa8146452adff3',
    messagingSenderId: '184831115274',
    projectId: 'qpay-pos',
    authDomain: 'qpay-pos.firebaseapp.com',
    storageBucket: 'qpay-pos.appspot.com',
    measurementId: 'G-3EF5KLGM2T',
  );
}
